spring.application.name=cruddemo


# Add JDBC connection info
spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username=springstudent
spring.datasource.password=springstudent


# Turn off the spring banner
#spring.main.banner-mode=off


# Reduce logging level. Set logging level to warn
#logging.level.root=warn


# Adding logging configs to display SQL statements
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.orm.jdbc.bind=trace

# Configure JPA / Hibernate to auto create the database schema
# the "update" option will keep the existing data and only add new tables
#spring.jpa.hibernate.ddl-auto=update
